### ISSUE TITLE
make mxnet_android

### ISSUE THREAD

**Issue by someoneAlready** [edmBernard/DockerFiles#3]
Hi, edmBernard, with our docker file, I build libmxnet_predict.so still cannot work.

**Comment by edmBernard** [comment]
I answer on your other comment : https://github.com/apache/incubator-mxnet/issues/8707

**Comment by edmBernard** [comment]
@someoneAlready did you resolve your issue ?

**Comment by someoneAlready** [comment]
@edmBernard yeah, the issue was resolved.
