### ISSUE TITLE
sh: cmake_android_arm.sh: No such file or directory

### ISSUE THREAD

**Issue by kwanking** [edmBernard/DockerFiles#7]
command: sudo make mxnet_android
the error is :

Step 21/22 : RUN cd "$OPENCV_DIR/opencv-master/platforms/scripts" &&     sh cmake_android_arm.sh -DANDROID_NATIVE_API_LEVEL=21 -DBUILD_SHARED_LIBS=OFF -DBUILD_opencv_world=ON &&     cd ../build_android_arm &&     make -j$(nproc) &&     make install
 ---> Running in 6a5a75d963ec
sh: cmake_android_arm.sh: No such file or directory
The command '/bin/sh -c cd "$OPENCV_DIR/opencv-master/platforms/scripts" &&     sh cmake_android_arm.sh -DANDROID_NATIVE_API_LEVEL=21 -DBUILD_SHARED_LIBS=OFF -DBUILD_opencv_world=ON &&     cd ../build_android_arm &&     make -j$(nproc) &&     make install' returned a non-zero code: 127
make: *** [Makefile:198: mxnet_android] Error 127

**Comment by edmBernard** [comment]
I've not update android target for a long time. Thanks for your feed back I will check to fix this.

**Comment by edmBernard** [comment]
@kwanking hi the fix was not so easy. I have to change every thing since opencv, mxnet and openblas don't work anymore. It will took me lot's of time.
If you just need mxnet on android, I advice you to use https://github.com/apache/incubator-mxnet/tree/master/ci with the command `./build.py -p armv7` you will have mxnet docker image with armv7 support lib

**Comment by kwanking** [comment]
@edmBernard thank you  very much! I will do.

**Comment by edmBernard** [comment]
Sorry for this long long delay. 
I have test a bit more for porting mxnet model to android. As of today, the amalgamation is not the good/easy way. this part of mxnet is and was not correctly maintain and up to date. It was often break by update. 
I think a better way to deploy mxnet model on android is to use tvm https://docs.tvm.ai/deploy/android.html
the pipelin will be : 
- MXnet model 
- use  TVM to create  .so model from mxnet model
- use TVM runtime to execute on Android
